### ISSUE TITLE
Inconsistent inspector colors

### ISSUE THREAD

**Issue by stesproject** [don-tnowe/godot-dictionary-inspector#19]
Hi,
thank you for this addon.
I installed it in Godot 4.3.stable and Godot 4.4.dev and I have the same issue: the color of the dictionaries in the inspector looks inconsistent
![image](https://github.com/user-attachments/assets/dc42383c-e1d0-4b92-b660-88a0fd7a5d96)
I didn't change anything in Godot Editor Theme settings.

**Comment by don-tnowe** [comment]
Why, of course it's consistent: the same color across all editors!

Can confirm, 4.3 stable. Seems the styleboxes were moved to another theme class. I will upload the fix soon.
