### ISSUE TITLE
How did you add property editors for elements?

### ISSUE THREAD

**Issue by M10241024** [don-tnowe/godot-dictionary-inspector#20]
When I create a PackedStringArray, how do you get the LineEdits for all the elements? Do you have to create a control node for each type manually, or is there a fuction that generates them automaticaly? (I looked at your code and it looks like you have to create them manually in "elements/base_property_editor.gd")

**Comment by don-tnowe** [comment]
Yes, `create_property_control_for_type()` in that script creates the proper control for a property type.

Is this for modifying how the plugin works?

**Comment by M10241024** [comment]
I wanted to make my own inspector plugin and allow to edit sub-resources via sub-inspectors, but I guess I would have to make the sub-inspector myself.

**Comment by don-tnowe** [comment]
Yeah, Unity Engine's editor has this feature but in Godot you must do this yourself. The number and resource pickers are nice, though.

You could also `edit_resource()` to open the inspector in full instead of a subinspector, but yeah, that's not very integrated :/
