### ISSUE TITLE
modifying type use index of option instead of id

### ISSUE THREAD

**Issue by ajreckof** [don-tnowe/godot-dictionary-inspector#7]
modifying type use the index of the option selected instead of the id of the option which results in for example, RID being created when Object is selected Object being created when Dictionary is selected, etc.

**Comment by Okxa** [comment]
Fix for this is included for godot 4 branch in #6, the fix could be used for godot 3 branch too.

**Comment by ajreckof** [comment]
nice hope the author will accept your pull request and put in on the asset store
